name: C Program Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install MinGW for cross-compiling
        run: |
          sudo apt update
          sudo apt install -y mingw-w64 make

      - name: Compile C program using Makefile
        run: make

      - name: Run tests (example)
        run: |
          # Example of running the compiled server and client (assuming they are set to run in test mode)
          ./server.exe &
          SERVER_PID=$!
          sleep 2  # Wait for server to initialize
          ./client.exe
          kill $SERVER_PID  # Stop server after test

      - name: Clean up
        run: make clean
