name: C Program Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install MinGW for cross-compiling
        run: |
          choco install mingw
          
      - name: Compile C program using Makefile
        run: make

      - name: Run tests (example)
        run: |
          # Run server and client directly on Windows
          Start-Process -NoNewWindow -FilePath ./server.exe
          Start-Process -NoNewWindow -FilePath ./client.exe

      - name: Clean up
        run: make clean
